/**
 * Pipeline image des items.
 *
 * Convention : un item dont le `templateId` figure dans `ITEMS_WITH_IMAGE`
 * dispose d'un fichier à `public/items/{templateId}.png`.
 *
 * Pour ajouter une image :
 *   1. Générer le PNG (voir prompts dans docs ou /agent)
 *   2. Le placer dans `public/items/{templateId}.png`
 *   3. Ajouter le `templateId` dans le Set ci-dessous
 *
 * Le composant `<ItemImage />` se charge ensuite du fallback (icône catégorie)
 * si le `templateId` n'est pas dans le Set.
 */

export const ITEMS_WITH_IMAGE: ReadonlySet<string> = new Set<string>([
  // Hors-musique (premiers tests)
  "jx.monopoly_80s",
  "ma.tabouret_bois_patine",

  // Musique — communs
  "mus.vinyle_pink_floyd_wall",
  "mus.vinyle_telephone_dure_limite",
  "mus.33tours_jazz_inconnu",
  "mus.cd_nirvana_in_utero",
  "mus.harmonica_hohner",
  "mus.vinyle_brel_amsterdam",
  "mus.vinyle_brassens_jeanne",
  "mus.vinyle_aznavour_emmenez",
  "mus.vinyle_piaf_non",
  "mus.vinyle_beatles_abbey_road",
  "mus.vinyle_stones_let_bleed",
  "mus.vinyle_bowie_ziggy",
  "mus.vinyle_zeppelin_iv",
  "mus.vinyle_dylan_blonde",
  "mus.vinyle_indochine_aventurier",
  "mus.vinyle_mylene_farmer_ainsi",
  "mus.vinyle_renaud_morgane",
  "mus.vinyle_hallyday_rock_memphis",
  "mus.vinyle_sardou_lacs",
  "mus.vinyle_goldman_envole",
  "mus.vinyle_cabrel_hors_saison",
  "mus.vinyle_gainsbourg_melody",
  "mus.vinyle_higelin_alertez",
  "mus.vinyle_balavoine_aziza",
  "mus.vinyle_souchon_foule",
  "mus.cd_daft_punk_homework",
  "mus.cd_radiohead_ok",
  "mus.cd_noir_desir_666",
  "mus.cd_iam_ecole",
  "mus.k7_audio_mixtape_90s",
  "mus.walkman_sony_wm",
  "mus.radio_cassette_sanyo",
  "mus.tourne_disque_thorens",
  "mus.partition_chopin",
  "mus.partition_satie",
  "mus.metronome_wittner",
  "mus.diapason_acier",
  "mus.flute_traversiere_yamaha",
  "mus.clarinette_buffet",
  "mus.ukulele_soprano",

  // Musique — rares
  "mus.guitare_classique_ancienne",
  "mus.vinyle_beatles_dedicace",
  "mus.vinyle_stones_test_pressing",
  "mus.guitare_gibson_les_paul",
  "mus.guitare_fender_strato_70s",
  "mus.accordeon_paolo_soprani",
  "mus.banjo_gibson_5cordes",
  "mus.violon_atelier_mirecourt",
  "mus.theremine_moog",
  "mus.synthe_moog_minimoog",
  "mus.boite_musique_mecanique",
  "mus.saxophone_selmer_mark_vi",

  // Musique — légendaires & unique
  "leg.mus.stradivarius",
  "leg.mus.piano_pleyel_concert",
  "leg.mus.guitare_hendrix_provenance",
  "uniq.mus.violon_paganini",

  // Jeux & Loisirs — communs
  "jx.cartouche_mario",
  "jx.manette_megadrive",
  "jx.gameboy_color_violette",
  "jx.ps1_crash_bandicoot",
  "jx.risk_1992",
  "jx.cartouche_zelda_nes",
  "jx.cartouche_megaman_nes",
  "jx.cartouche_sonic_megadrive",
  "jx.cartouche_streetfighter_snes",
  "jx.console_snes_complete",
  "jx.console_nes_japonaise",
  "jx.console_atari_2600",
  "jx.console_dreamcast_complete",
  "jx.console_ps2_jeux",
  "jx.manette_dualshock1",
  "jx.manette_n64",
  "jx.jeu_ps1_resident_evil",
  "jx.jeu_ps1_metal_gear",
  "jx.jeu_dreamcast_shenmue",
  "jx.jeu_n64_zelda_oot",
  "jx.magic_lot_revised",
  "jx.lot_yu_gi_oh",
  "jx.lot_pokemon_jungle",
  "jx.trivial_pursuit_genus",
  "jx.cluedo_vintage",
  "jx.mille_bornes_60s",
  "jx.petits_chevaux_bois",
  "jx.echecs_buis_acajou",
  "jx.backgammon_cuir",
  "jx.dominos_os",
  "jx.yo_yo_duncan_alu",
  "jx.billes_verre_lot",
  "jx.soldat_plomb_napoleonien",
  "jx.petite_armee_plomb",
  "jx.peluche_ours_steiff",
  "jx.poupee_porcelaine_ancienne",
  "jx.barbie_seventies",
  "jx.figurine_smurfs_lot",
  "jx.figurine_kinder_lot",
  // Jeux & Loisirs — rares
  "jx.cartes_pokemon_1ere_edition",
  "jx.figurine_star_wars_kenner_78",
  "jx.figurine_starwars_dark_vador_kenner",
  "jx.flipper_gottlieb_60s",
  "jx.borne_arcade_mini",
  "jx.cartes_pokemon_japan_holo",
  "jx.cartouche_chrono_trigger",
  "jx.console_neogeo_aes",
  "jx.train_marklin_ho",
  "jx.lego_pirate_complete",
  "jx.figurine_he_man_origines",
  "jx.peluche_steiff_ours_1920",
  // Jeux & Loisirs — légendaires & unique
  "leg.jx.cartouche_stadium_events",
  "leg.jx.babyfoot_bonzini_itsf",
  "leg.jx.cartouche_nwc_1990",
  "uniq.jx.console_pong_1972",

  // Bricolage — communs
  "br.marteau_menuisier",
  "br.boite_outils_complete",
  "br.etabli_pliant_ancien",
  "br.pince_etirer_cuivre",
  "br.scie_egoine_stanley",
  "br.scie_arc_charpentier",
  "br.scie_japonaise_recente",
  "br.marteau_arracheur",
  "br.masse_fer_forge",
  "br.tournevis_lot_ancien",
  "br.cle_anglaise_old",
  "br.cle_a_molette_ancienne",
  "br.niveau_a_bulle_laiton",
  "br.metre_pliant_bois_2m",
  "br.equerre_metallique",
  "br.pied_a_coulisse_acier",
  "br.perceuse_a_manivelle",
  "br.fer_a_souder_vintage",
  "br.boite_quincaillerie_metal",
  "br.lot_vis_clous_anciens",
  "br.enclume_petit_modele",
  "br.etau_de_table_regulier",
  "br.lampe_baladeuse_atelier",
  "br.etabli_chene_atelier",
  "br.caisse_outils_chene",
  "br.lot_limes_charpentier",
  "br.ciseaux_a_bois_lot",
  "br.varlope_chene",
  "br.rabot_stanley_no4",
  "br.rabot_bois_artisanal",
  "br.gouge_sculpteur_lot",
  "br.trusquin_acajou_laiton",
  "br.compas_charpentier_xixe",
  "br.mortaisier_acier",
  "br.tariere_charpentier",
  "br.tenailles_forgeron",
  "br.serre_joints_lot",
  "br.plane_charronnier",
  "br.marteau_horloger",
  "br.tournevis_horloger_lot",
  // Bricolage — rares
  "br.outils_peugeot_freres",
  "br.scie_disston_no7",
  "br.rabot_stanley_bedrock",
  "br.coffret_ebeniste_xixe",
  "br.etabli_compagnonnage_xixe",
  "br.singer_fonte_xixe",
  "br.tour_a_bois_atelier",
  "br.enclume_grande_forge",
  "br.outils_compagnon_devoir",
  "br.coffret_dessin_industriel",
  "br.tariere_grande_xviiie",
  "br.balance_romaine_fonte",
  // Bricolage — légendaires & unique
  "leg.br.scie_japonaise_edo",
  "leg.br.coffret_compagnon_signe",
  "leg.br.tour_holtzapffel_xixe",
  "uniq.br.coffre_outils_louis_xiv",

  // Mode — communs
  "mo.veste_jean_delavee",
  "mo.blouson_cuir_vintage",
  "mo.chapeau_feutre_50s",
  "mo.robe_70s_disco",
  "mo.robe_80s_epaulettes",
  "mo.robe_50s_pinup",
  "mo.robe_60s_mini",
  "mo.jupe_plissee_60s",
  "mo.pantalon_pattes_eph",
  "mo.chemise_lacoste_originale",
  "mo.polo_lacoste_pique",
  "mo.trench_burberry_classique",
  "mo.manteau_lainage_60s",
  "mo.chaussures_richelieu_cuir",
  "mo.escarpins_seconde_main",
  "mo.bottes_camperos_cuir",
  "mo.sac_seventies_cuir",
  "mo.ceinture_cuir_laiton",
  "mo.foulard_soie_motifs",
  "mo.carre_hermes_recent",
  "mo.chapeau_panama_montecristi",
  "mo.chapeau_borsalino",
  "mo.casquette_gavroche_60s",
  "mo.gants_cuir_femme",
  "mo.ombrelle_dentelle_xixe",
  "mo.eventail_nacre",
  "mo.broche_pinup_strass",
  "mo.broche_camee_xixe",
  "mo.bracelet_jonc_argent",
  "mo.collier_perles_culture",
  "mo.bague_chevaliere_argent",
  "mo.boucles_oreilles_perles",
  "mo.epingle_cravate_strass",
  "mo.montre_lip_dauphine",
  "mo.montre_yema_superman",
  "mo.montre_seiko_5_vintage",
  "mo.cravate_charvet_soie",
  "mo.cravate_club_anglaise",
  "mo.ceinture_hermes_h_recente",
  "mo.portefeuille_lv_monogram",
  // Mode — rares
  "mo.sac_lancel",
  "mo.broche_emaillee_artdeco",
  "mo.sac_hermes_kelly",
  "mo.sac_chanel_classic",
  "mo.sac_celine_phantom",
  "mo.manteau_burberry_couture_60s",
  "mo.tailleur_chanel_70s",
  "mo.chemise_dior_homme",
  "mo.veste_ysl_smoking_80s",
  "mo.collier_van_cleef_alhambra",
  "mo.bague_cartier_trinity",
  "mo.foulard_hermes_brides",
  // Mode — légendaires & unique
  "leg.mo.robe_chanel_1925",
  "leg.mo.dior_new_look_1955",
  "leg.mo.birkin_himalaya",
  "uniq.mo.bijou_marie_antoinette",

  // Objets d'art — communs
  "art.aquarelle_paysage_anonyme",
  "art.gravure_ancienne_xixe",
  "art.terre_cuite_buste",
  "art.serigraphie_pop_signee",
  "art.masque_tribal_decoratif",
  "art.bronze_animalier",
  "art.aquarelle_marine_xixe",
  "art.aquarelle_paysage_provencal",
  "art.pastel_portrait_femme",
  "art.dessin_fusain_atelier",
  "art.lithographie_signee_xxe",
  "art.litho_chagall_planche",
  "art.gravure_durer_reimpr",
  "art.gravure_jouy_paris",
  "art.estampe_hokusai_edition",
  "art.estampe_hiroshige_paysage",
  "art.terre_cuite_putto",
  "art.terre_cuite_femme_classique",
  "art.bronze_buste_voltaire",
  "art.bronze_barye_style",
  "art.bronze_petite_danseuse",
  "art.platre_atelier_torse",
  "art.masque_inuit_inspiration",
  "art.statue_bouddha_pierre",
  "art.statuette_egyptienne_inspi",
  "art.huile_anonyme_xixe",
  "art.peinture_naive_paysanne",
  "art.nature_morte_xixe_cadre",
  "art.portrait_bourgeois_xixe",
  "art.icone_orthodoxe_bois",
  "art.icone_russe_doree",
  "art.plaque_email_limoges",
  "art.vase_lallemant_polychrome",
  "art.coupe_emaillee_longwy_art",
  "art.boite_laquee_japonaise",
  "art.petite_sculpture_ivoire",
  "art.miniature_portrait_dame",
  "art.assiette_picasso_style",
  "art.eventail_chinois_peint",
  "art.boite_marqueterie_florentine",
  // Objets d'art — rares
  "art.dessin_signe_ecole_francaise",
  "art.vase_galle_signe",
  "art.litho_picasso_signe_planche",
  "art.dessin_dali_signe",
  "art.gravure_rembrandt_reimpr",
  "art.bronze_giacometti_planche",
  "art.huile_corot_attribuee",
  "art.vase_lalique_signe",
  "art.sculpture_rodin_planche",
  "art.estampe_picasso_signee",
  "art.aquarelle_dufy_signee",
  "art.toile_buffet_signee",
  // Objets d'art — légendaires & unique
  "leg.art.dessin_picasso_etude",
  "leg.art.dessin_matisse_etude",
  "leg.art.toile_chagall_attribuee",
  "uniq.art.toile_monet_inedite",
]);

export function getItemImageUrl(templateId: string): string | null {
  return ITEMS_WITH_IMAGE.has(templateId)
    ? `/items/${templateId}.png`
    : null;
}
