/**
 * Pipeline image des items.
 *
 * Convention : un item dont le `templateId` figure dans `ITEMS_WITH_IMAGE`
 * dispose d'un fichier à `public/items/{templateId}.png`.
 *
 * Pour ajouter une image :
 *   1. Générer le PNG (voir prompts dans docs ou /agent)
 *   2. Le placer dans `public/items/{templateId}.png`
 *   3. Ajouter le `templateId` dans le Set ci-dessous
 *
 * Le composant `<ItemImage />` se charge ensuite du fallback (icône catégorie)
 * si le `templateId` n'est pas dans le Set.
 */

export const ITEMS_WITH_IMAGE: ReadonlySet<string> = new Set<string>([
  // Hors-musique (premiers tests)
  "jx.jeu_magnatimmo_annees_80",
  "ma.tabouret_bois_patine",

  // Musique — communs
  "mus.vinyle_des_loups_des_steppes_bark_to_be_free",
  "mus.vinyle_grand_max_des_combines",
  "mus.33tours_jazz_1",
  "mus.coffret_cd_grunge_beatitude",
  "mus.harmonica_chromatique_de_bluesman",
  "mus.vinyle_stevranos_vive_la_fet_a",
  "mus.vinyle_victor_de_la_brasse_bibelot",
  "mus.vinyle_paul_nazamour_demain_enfin",
  "mus.vinyle_judith_loiseau_oui_je_regrette_tout",
  "mus.vinyle_des_scarabees_passage_cloute",
  "mus.vinyle_des_trolling_sons_bet_it_heal",
  "mus.vinyle_du_david_bah_oui_comete",
  "mus.vinyle_free_robot_des_punkbot",
  "mus.33tours_jazz_2",
  "mus.33tours_jazz_3",
  "mus.vinyle_de_la_rousse_mystique_ainsi_soit_elle",
  "mus.vinyle_renaut_megane_sans_toit",
  "mus.vinyle_hollyday_caillou_a_woippy",
  "mus.vinyle_les_pates_carbonnara_michele_sardaigna",
  "mus.vinyle_silverguy_moi_au_volant",
  "mus.vinyle_francois_cabriol_hors_piste",
  "mus.vinyle_concept_laga_jagavaganaigase_du_dandy_a",
  "mus.vinyle_classique_incontournable_classique",
  "mus.vinyle_miguel_pavane_la_zizanie",
  "mus.vinyle_whale_song_son_terrestre_n1",
  "mus.cd_bad_luck_des_punkbot",
  "mus.cd_ok_ai_frequencies",
  "mus.cd_club_67_souhait_obscur",
  "mus.cd_le_micro_argente_nou",
  "mus.k7_audio_mixtape_90s",
  "mus.baladeur_a_cassette_annees_80",
  "mus.radio_cassette_annees_80",
  "mus.tourne_disque_a_courroie_vintage",
  "mus.partition_chopin",
  "mus.partition_satie",
  "mus.metronome_mecanique_a_pyramide",
  "mus.diapason_acier",
  "mus.flute_traversiere_argentee",
  "mus.clarinette_en_ebene",
  "mus.ukulele_soprano",

  // Musique — rares
  "mus.guitare_classique_ancienne",
  "mus.vinyle_collector_de_vagabond_horizon_celeste",
  "mus.test_pressing_des_trolling_sons",
  "mus.guitare_electrique_a_corps_plein_modele_legend",
  "mus.guitare_electrique_a_trois_micros_solid_body_1",
  "mus.accordeon_italien_signe",
  "mus.banjo_5_cordes_ancien",
  "mus.violon_atelier_mirecourt",
  "mus.theremine_a_antennes",
  "mus.synthetiseur_analogique_mini_1970",
  "mus.boite_musique_mecanique",
  "mus.saxophone_alto_professionnel",

  // Musique — légendaires & unique
  "leg.mus.violon_de_maitre_cremonais_1715",
  "leg.mus.piano_a_queue_de_concert_1900",
  "leg.mus.guitare_de_legende_de_johny_perdrix_jouee_a_l",
  "uniq.mus.violon_paganini",

  // Jeux & Loisirs — communs
  "jx.cartouche_le_plombier_sauteur_8_bit",
  "jx.manette_megadrive",
  "jx.playbox_pocket",
  "jx.jeu_foxy_crush_32_bit",
  "jx.risk_1992",
  "jx.cartouche_la_legende_de_solda_8_bit",
  "jx.cartouche_bluebot_8_bit",
  "jx.cartouche_turbo_herisson_16_bit",
  "jx.cartouche_street_castagne_ii_16_bit",
  "jx.super_console_16_bit_complete",
  "jx.console_familiale_8_bit_japonaise",
  "jx.console_de_salon_a_cartouches_annees_70",
  "jx.console_128_bit_reve_complete",
  "jx.console_de_salon_128_bit_avec_jeux",
  "jx.manette_vibraduo",
  "jx.manette_tetrapod_64_bit",
  "jx.jeu_le_manoir_du_mal_32_bit",
  "jx.jeu_engrenage_de_metal_infiltration_32_bit",
  "jx.jeu_d_aventure_japonais_128_bit",
  "jx.jeu_solda_flute_temporelle_aventure_3d_64_bit",
  "jx.lot_de_cartes_l_assemblee_des_mages",
  "jx.lot_de_cartes_de_yo_hi_ah",
  "jx.cartes_pocket_monster_set_jungle",
  "jx.jeu_question_pour_un_fromage_culture_generale",
  "jx.jeu_kicekatue_mr_mayonnaise_vintage",
  "jx.jeu_de_cartes_long_trajet_annees_60",
  "jx.petits_chevaux_bois",
  "jx.echecs_buis_acajou",
  "jx.backgammon_cuir",
  "jx.dominos_os",
  "jx.yo_yo_duncan_alu",
  "jx.billes_verre_lot",
  "jx.soldat_plomb_napoleonien",
  "jx.petite_armee_plomb",
  "jx.ours_en_peluche_mohair_recent",
  "jx.poupee_porcelaine_ancienne",
  "jx.poupee_barberousse_annees_70",
  "jx.lot_de_figurines_de_spountch",
  "jx.lot_de_figurines_d_ufs_surprises",
  // Jeux & Loisirs — rares
  "jx.cartes_pocket_monster_1ere_edition",
  "jx.figurine_de_guerre_galactique_1978",
  "jx.figurine_de_dark_father_1977",
  "jx.flipper_a_plateau_annees_60",
  "jx.borne_arcade_mini",
  "jx.cartes_pocket_monster_holographiques_japonaise",
  "jx.cartouche_gachette_du_temps_rpg_16_bit",
  "jx.console_d_arcade_domestique_neo",
  "jx.train_electrique_ho_de_precision",
  "jx.grand_set_de_briques_pirates_complet",
  "jx.figurine_du_capitaine_muscle_origines",
  "jx.ours_en_peluche_mohair_annees_1920",
  // Jeux & Loisirs — légendaires & unique
  "leg.jx.cartouche_stadium_events",
  "leg.jx.baby_foot_de_competition_minibon_homologue",
  "leg.jx.cartouche_nwc_1990",
  "uniq.jx.prototype_de_la_toute_premiere_console_de_jeu",

  // Bricolage — communs
  "br.marteau_menuisier",
  "br.boite_outils_complete",
  "br.etabli_pliant_ancien",
  "br.pince_etirer_cuivre",
  "br.scie_egoine_de_charpentier",
  "br.scie_arc_charpentier",
  "br.scie_japonaise_recente",
  "br.marteau_arracheur",
  "br.masse_fer_forge",
  "br.tournevis_lot_ancien",
  "br.cle_anglaise_old",
  "br.cle_a_molette_ancienne",
  "br.niveau_a_bulle_laiton",
  "br.metre_pliant_bois_2m",
  "br.equerre_metallique",
  "br.pied_a_coulisse_acier",
  "br.perceuse_a_manivelle",
  "br.fer_a_souder_vintage",
  "br.boite_quincaillerie_metal",
  "br.lot_vis_clous_anciens",
  "br.enclume_petit_modele",
  "br.etau_de_table_regulier",
  "br.lampe_baladeuse_atelier",
  "br.etabli_chene_atelier",
  "br.caisse_outils_chene",
  "br.lot_limes_charpentier",
  "br.ciseaux_a_bois_lot",
  "br.varlope_chene",
  "br.rabot_metallique_n4_d_ebeniste",
  "br.rabot_bois_artisanal",
  "br.gouge_sculpteur_lot",
  "br.trusquin_acajou_laiton",
  "br.compas_charpentier_xixe",
  "br.mortaisier_acier",
  "br.tariere_charpentier",
  "br.tenailles_forgeron",
  "br.serre_joints_lot",
  "br.plane_charronnier",
  "br.marteau_horloger",
  "br.tournevis_horloger_lot",
  // Bricolage — rares
  "br.boite_d_outils_de_manufacture_signee",
  "br.scie_a_dos_de_menuisier_n7_ancienne",
  "br.rabot_d_ebeniste_a_semelle_modele_605",
  "br.coffret_ebeniste_xixe",
  "br.etabli_de_compagnonnage_xixe",
  "br.machine_a_coudre_en_fonte_a_pedale_xixe",
  "br.tour_a_bois_atelier",
  "br.enclume_grande_forge",
  "br.lot_d_outils_de_compagnon_du_tour_de_france",
  "br.coffret_dessin_industriel",
  "br.tariere_grande_xviiie",
  "br.balance_romaine_fonte",
  // Bricolage — légendaires & unique
  "leg.br.scie_japonaise_edo",
  "leg.br.coffret_d_outils_de_compagnon",
  "leg.br.tour_a_metaux_d_orfevre_de_prestige_xixe",
  "uniq.br.coffre_outils_louis_xiv",

  // Mode — communs
  "mo.veste_jean_delavee",
  "mo.blouson_cuir_vintage",
  "mo.chapeau_feutre_50s",
  "mo.robe_70s_disco",
  "mo.robe_80s_epaulettes",
  "mo.robe_50s_pinup",
  "mo.robe_60s_mini",
  "mo.jupe_plissee_60s",
  "mo.pantalon_pattes_eph",
  "mo.chemise_golgothor_70s",
  "mo.polo_golgothor",
  "mo.trench_coat_berrybeurre",
  "mo.manteau_lainage_60s",
  "mo.chaussures_richelieu_cuir",
  "mo.escarpins_seconde_main",
  "mo.bottes_camperos_cuir",
  "mo.sac_seventies_cuir",
  "mo.ceinture_cuir_laiton",
  "mo.foulard_soie_motifs",
  "mo.carre_de_soie_talaria_recent",
  "mo.chapeau_panama_montecristi",
  "mo.chapeau_de_feutre_italien_a_large_bord",
  "mo.casquette_gavroche_60s",
  "mo.gants_cuir_femme",
  "mo.ombrelle_en_dentelle_xixe",
  "mo.eventail_nacre",
  "mo.broche_pinup_strass",
  "mo.broche_camee_xixe",
  "mo.bracelet_jonc_argent",
  "mo.collier_perles_culture",
  "mo.bague_chevaliere_argent",
  "mo.boucles_oreilles_perles",
  "mo.epingle_cravate_strass",
  "mo.montre_doree_vintage",
  "mo.montre_de_plongee_vintage",
  "mo.montre_automatique_vintage",
  "mo.cravate_en_soie_de_luxe",
  "mo.cravate_club_anglaise",
  "mo.ceinture_talaria",
  "mo.portefeuille_polis_futton",
  // Mode — rares
  "mo.sac_a_main_cancel",
  "mo.broche_emaillee_artdeco",
  "mo.sac_a_main_talaria",
  "mo.sac_chaine",
  "mo.sac_cedrine_tempome",
  "mo.manteau_berrybeurre",
  "mo.tailleur_chaine_annees_70",
  "mo.chemise_ridor",
  "mo.veste_smoking_msg",
  "mo.collier_a_motifs_trefle_porte_bonheur",
  "mo.bague_a_trois_anneaux_d_or_occasion",
  "mo.carre_de_soie_talaria_ancien",
  // Mode — légendaires & unique
  "leg.mo.la_petite_robe_noire_chaine_1925",
  "leg.mo.robe_ridor_new_look_1955",
  "leg.mo.birkin_himalaya",
  "uniq.mo.bijou_marie_antoinette",

  // Objets d'art — communs
  "art.aquarelle_paysage_anonyme",
  "art.gravure_ancienne_xixe",
  "art.terre_cuite_buste",
  "art.serigraphie_pop_signee",
  "art.masque_tribal_decoratif",
  "art.bronze_animalier",
  "art.aquarelle_marine_xixe",
  "art.aquarelle_paysage_provencal",
  "art.pastel_portrait_femme",
  "art.dessin_fusain_atelier",
  "art.lithographie_signee_xxe",
  "art.lithographie_de_chacal_planche",
  "art.gravure_durer_reimpr",
  "art.gravure_jouy_paris",
  "art.estampe_hokusai_edition",
  "art.estampe_hiroshige_paysage",
  "art.terre_cuite_putto",
  "art.terre_cuite_femme_classique",
  "art.bronze_buste_voltaire",
  "art.bronze_barye_style",
  "art.bronze_petite_danseuse",
  "art.platre_atelier_torse",
  "art.masque_inuit_inspiration",
  "art.statue_bouddha_pierre",
  "art.statuette_egyptienne_inspi",
  "art.huile_anonyme_xixe",
  "art.peinture_naive_paysanne",
  "art.nature_morte_xixe_cadre",
  "art.portrait_bourgeois_xixe",
  "art.icone_orthodoxe_bois",
  "art.icone_russe_doree",
  "art.plaque_email_limoges",
  "art.vase_art_deco_bebert_germain",
  "art.coupe_emaillee_longwy_art",
  "art.boite_laquee_japonaise",
  "art.petite_sculpture_ivoire",
  "art.miniature_portrait_dame",
  "art.assiette_decorative_signee_picassiette",
  "art.eventail_chinois_peint",
  "art.boite_marqueterie_florentine",
  // Objets d'art — rares
  "art.dessin_signe_ecole_francaise",
  "art.vase_galle_signe",
  "art.lithographie_cubiste_signee_picassiette_planch",
  "art.dessin_surrealiste_aux_montres_molles_signe",
  "art.gravure_rembrandt_reimpr",
  "art.bronze_d_atelier_aux_silhouettes_filiformes_pl",
  "art.huile_corot_attribuee",
  "art.vase_en_verre_moule_laluck_signe",
  "art.petite_sculpture_rondin_planche",
  "art.estampe_cubiste_signee_picassiette",
  "art.aquarelle_fauviste_de_roland_duff_signee",
  "art.toile_expressionniste_de_bebert_bahut_signee",
  // Objets d'art — légendaires & unique
  "leg.art.dessin_cubiste_signe_picassiette_etude",
  "leg.art.dessin_fauviste_aux_gouaches_decoupees_etude",
  "leg.art.toile_onirique_de_chacal_etude",
  "uniq.art.toile_monet_inedite",

  // Livres & Papeterie — communs
  "lv.monte_cristo",
  "lv.les_aventures_de_titou_cap_sur_la_lune",
  "lv.paris_match_70s",
  "lv.cartes_postales_anciennes",
  "lv.miserables_pleiade",
  "lv.rouge_noir_coffret",
  "lv.bovary_relie",
  "lv.proust_recherche_folio",
  "lv.zola_germinal_xixe",
  "lv.camus_etranger",
  "lv.sartre_nausee",
  "lv.colette_cheri_relie",
  "lv.simone_beauvoir_deuxieme",
  "lv.duras_amant",
  "lv.le_petit_moustachu_reimpression",
  "lv.le_petit_moustachu_zbeul_au_village",
  "lv.funky_look_les_freres_bandots",
  "lv.roupille_et_queue_longue",
  "lv.le_lieutenant_du_far_west",
  "lv.le_marin_reveur_la_ballade",
  "lv.les_histoires_du_petit_ecolier",
  "lv.encyclopedie_quillet_lot",
  "lv.larousse_universel_2vol",
  "lv.dictionnaire_robert_70s",
  "lv.atlas_michelin_60s",
  "lv.livre_recettes_curnonsky",
  "lv.livres_scolaires_anciens",
  "lv.cahier_ecolier_seyes",
  "lv.encrier_porcelaine_xixe",
  "lv.plume_sergent_major",
  "lv.stylo_waterman_vintage",
  "lv.papier_filigrane_lot",
  "lv.magazine_geo_lot",
  "lv.magazine_lui_60s",
  "lv.les_aventures_de_titou_l_affaire_du_professeur",
  "lv.almanach_vermot",
  "lv.carte_marine_xixe",
  "lv.lampe_huile_biblio",
  "lv.coffret_loupes_lecture",
  "lv.album_photos_velours",
  // Livres & Papeterie — rares
  "lv.conte_de_l_aviateur_et_de_l_enfant_roi_edition",
  "lv.les_aventures_de_titou_petrole_1950",
  "lv.le_petit_moustachu_edition_originale_1961",
  "lv.funky_look_premier_album_1947",
  "lv.proust_swann_dedicace",
  "lv.hugo_legende_relie_cuir",
  "lv.atlas_diderot_planche",
  "lv.livre_heures_xviie",
  "lv.bible_olivetan_xvie",
  "lv.cartes_postales_belle_epoque_rare",
  "lv.stylo_plume_haut_de_gamme_a_l_etoile_blanche_d",
  "lv.encrier_argent_xixe",
  // Livres & Papeterie — légendaires & unique
  "leg.lv.miserables_originale",
  "leg.lv.gutenberg_feuillet",
  "leg.lv.manuscrit_enlumine_xve",
  "uniq.lv.manuscrit_voltaire",

  // Maison — communs
  "ma.figurine_porcelaine",
  "ma.statuette_africaine_bois",
  "ma.service_the_faience",
  "ma.verres_a_pied_lot6",
  "ma.vase_en_cristal_baraka",
  "ma.vase_en_verre_moule_laluck_recent",
  "ma.carafe_cristal_taille",
  "ma.service_porcelaine_limoges",
  "ma.plat_faience_olympe",
  "ma.saliere_argent_minerve",
  "ma.timbale_argent_bapteme",
  "ma.coupe_emaillee_longwy",
  "ma.plat_en_ceramique_de_vallauris_signe_picassiet",
  "ma.cendrier_en_pate_de_cristal_dome",
  "ma.menagere_en_metal_argente_24_pieces",
  "ma.service_the_chinois",
  "ma.tasses_porcelaine_paris",
  "ma.pichet_faience_emaillee",
  "ma.bougeoirs_laiton_louisxv",
  "ma.horloge_carillon_westminster",
  "ma.pendule_marbre_xixe",
  "ma.pendule_voyage_laiton",
  "ma.miroir_psyche",
  "ma.miroir_baroque_petit",
  "ma.gueridon_salon",
  "ma.coffre_chinois_laque",
  "ma.service_liqueur_cristal",
  "ma.bonbonniere_porcelaine",
  "ma.saliere_poivriere_argent",
  "ma.plateau_marqueterie",
  "ma.nature_morte_xixe_cadre",
  "ma.pendulette_bronze",
  "ma.lampe_petrole_ancienne",
  "ma.lampe_globe_opaline",
  "ma.service_cafe_faience",
  "ma.saladier_verre_boheme",
  "ma.cafetiere_emaillee_50s",
  "ma.seau_a_glace_plaque",
  "ma.lustre_bronze_cristal_petit",
  // Maison — rares
  "ma.boite_musique_ancienne",
  "ma.lampe_bureau_artdeco",
  "ma.miroir_dore_fronton",
  "ma.service_a_the_en_porcelaine_de_saxe_6_tasses",
  "ma.vase_en_pate_de_verre_dome_signe",
  "ma.lustre_en_cristal_baraka",
  "ma.commode_louis_xv_marqueterie",
  "ma.tapis_persan_ispahan",
  "ma.pendule_d_horloger_braguette_signee",
  "ma.candelabre_argent_5branches",
  "ma.menagere_en_argent_massif_36_pieces",
  "ma.bibliotheque_louis_philippe",
  // Maison — légendaires & unique
  "leg.ma.uf_joaillier_imperial_en_email_replique",
  "leg.ma.tapis_savonnerie_xviie",
  "leg.ma.pendule_louis_xiv_boulle",
  "uniq.ma.vase_ming_dynasty",
]);

/**
 * Retourne le chemin du WebP de l'item (généré par `scripts/generate-webp.mjs`).
 * Supporté nativement par tous les navigateurs cibles (Tauri WebKit/WebView2
 * + browsers modernes).
 */
export function getItemImageUrl(templateId: string): string | null {
  return ITEMS_WITH_IMAGE.has(templateId)
    ? `/items/${templateId}.webp`
    : null;
}

/**
 * Retourne le chemin de la vignette de l'item (max 384 px, générée par
 * `scripts/generate-item-thumbs.mjs`). À utiliser dans les listes/grilles
 * denses : décoder le plein format (~1600 px) pour des centaines de cellules
 * fait exploser la mémoire (sous iOS, le WebView recharge la page). La vignette
 * se décode ~20× plus léger. Les vues « plein écran » (overlay détail) gardent
 * `getItemImageUrl`.
 */
export function getItemThumbUrl(templateId: string): string | null {
  return ITEMS_WITH_IMAGE.has(templateId)
    ? `/items/thumbs/${templateId}.webp`
    : null;
}
