/**
 * Pipeline image des items.
 *
 * Convention : un item dont le `templateId` figure dans `ITEMS_WITH_IMAGE`
 * dispose d'un fichier à `public/items/{templateId}.png`.
 *
 * Pour ajouter une image :
 *   1. Générer le PNG (voir prompts dans docs ou /agent)
 *   2. Le placer dans `public/items/{templateId}.png`
 *   3. Ajouter le `templateId` dans le Set ci-dessous
 *
 * Le composant `<ItemImage />` se charge ensuite du fallback (icône catégorie)
 * si le `templateId` n'est pas dans le Set.
 */

export const ITEMS_WITH_IMAGE: ReadonlySet<string> = new Set<string>([
  // Hors-musique (premiers tests)
  "jx.monopoly_80s",
  "ma.tabouret_bois_patine",

  // Musique — communs
  "mus.vinyle_pink_floyd_wall",
  "mus.vinyle_telephone_dure_limite",
  "mus.33tours_jazz_inconnu",
  "mus.cd_nirvana_in_utero",
  "mus.harmonica_hohner",
  "mus.vinyle_brel_amsterdam",
  "mus.vinyle_brassens_jeanne",
  "mus.vinyle_aznavour_emmenez",
  "mus.vinyle_piaf_non",
  "mus.vinyle_beatles_abbey_road",
  "mus.vinyle_stones_let_bleed",
  "mus.vinyle_bowie_ziggy",
  "mus.vinyle_zeppelin_iv",
  "mus.vinyle_dylan_blonde",
  "mus.vinyle_indochine_aventurier",
  "mus.vinyle_mylene_farmer_ainsi",
  "mus.vinyle_renaud_morgane",
  "mus.vinyle_hallyday_rock_memphis",
  "mus.vinyle_sardou_lacs",
  "mus.vinyle_goldman_envole",
  "mus.vinyle_cabrel_hors_saison",
  "mus.vinyle_gainsbourg_melody",
  "mus.vinyle_higelin_alertez",
  "mus.vinyle_balavoine_aziza",
  "mus.vinyle_souchon_foule",
  "mus.cd_daft_punk_homework",
  "mus.cd_radiohead_ok",
  "mus.cd_noir_desir_666",
  "mus.cd_iam_ecole",
  "mus.k7_audio_mixtape_90s",
  "mus.walkman_sony_wm",
  "mus.radio_cassette_sanyo",
  "mus.tourne_disque_thorens",
  "mus.partition_chopin",
  "mus.partition_satie",
  "mus.metronome_wittner",
  "mus.diapason_acier",
  "mus.flute_traversiere_yamaha",
  "mus.clarinette_buffet",
  "mus.ukulele_soprano",

  // Musique — rares
  "mus.guitare_classique_ancienne",
  "mus.vinyle_beatles_dedicace",
  "mus.vinyle_stones_test_pressing",
  "mus.guitare_gibson_les_paul",
  "mus.guitare_fender_strato_70s",
  "mus.accordeon_paolo_soprani",
  "mus.banjo_gibson_5cordes",
  "mus.violon_atelier_mirecourt",
  "mus.theremine_moog",
  "mus.synthe_moog_minimoog",
  "mus.boite_musique_mecanique",
  "mus.saxophone_selmer_mark_vi",

  // Musique — légendaires & unique
  "leg.mus.stradivarius",
  "leg.mus.piano_pleyel_concert",
  "leg.mus.guitare_hendrix_provenance",
  "uniq.mus.violon_paganini",

  // Jeux & Loisirs — communs
  "jx.cartouche_mario",
  "jx.manette_megadrive",
  "jx.gameboy_color_violette",
  "jx.ps1_crash_bandicoot",
  "jx.risk_1992",
  "jx.cartouche_zelda_nes",
  "jx.cartouche_megaman_nes",
  "jx.cartouche_sonic_megadrive",
  "jx.cartouche_streetfighter_snes",
  "jx.console_snes_complete",
  "jx.console_nes_japonaise",
  "jx.console_atari_2600",
  "jx.console_dreamcast_complete",
  "jx.console_ps2_jeux",
  "jx.manette_dualshock1",
  "jx.manette_n64",
  "jx.jeu_ps1_resident_evil",
  "jx.jeu_ps1_metal_gear",
  "jx.jeu_dreamcast_shenmue",
  "jx.jeu_n64_zelda_oot",
  "jx.magic_lot_revised",
  "jx.lot_yu_gi_oh",
  "jx.lot_pokemon_jungle",
  "jx.trivial_pursuit_genus",
  "jx.cluedo_vintage",
  "jx.mille_bornes_60s",
  "jx.petits_chevaux_bois",
  "jx.echecs_buis_acajou",
  "jx.backgammon_cuir",
  "jx.dominos_os",
  "jx.yo_yo_duncan_alu",
  "jx.billes_verre_lot",
  "jx.soldat_plomb_napoleonien",
  "jx.petite_armee_plomb",
  "jx.peluche_ours_steiff",
  "jx.poupee_porcelaine_ancienne",
  "jx.barbie_seventies",
  "jx.figurine_smurfs_lot",
  "jx.figurine_kinder_lot",
  // Jeux & Loisirs — rares
  "jx.cartes_pokemon_1ere_edition",
  "jx.figurine_star_wars_kenner_78",
  "jx.figurine_starwars_dark_vador_kenner",
  "jx.flipper_gottlieb_60s",
  "jx.borne_arcade_mini",
  "jx.cartes_pokemon_japan_holo",
  "jx.cartouche_chrono_trigger",
  "jx.console_neogeo_aes",
  "jx.train_marklin_ho",
  "jx.lego_pirate_complete",
  "jx.figurine_he_man_origines",
  "jx.peluche_steiff_ours_1920",
  // Jeux & Loisirs — légendaires & unique
  "leg.jx.cartouche_stadium_events",
  "leg.jx.babyfoot_bonzini_itsf",
  "leg.jx.cartouche_nwc_1990",
  "uniq.jx.console_pong_1972",

  // Bricolage — communs
  "br.marteau_menuisier",
  "br.boite_outils_complete",
  "br.etabli_pliant_ancien",
  "br.pince_etirer_cuivre",
  "br.scie_egoine_stanley",
  "br.scie_arc_charpentier",
  "br.scie_japonaise_recente",
  "br.marteau_arracheur",
  "br.masse_fer_forge",
  "br.tournevis_lot_ancien",
  "br.cle_anglaise_old",
  "br.cle_a_molette_ancienne",
  "br.niveau_a_bulle_laiton",
  "br.metre_pliant_bois_2m",
  "br.equerre_metallique",
  "br.pied_a_coulisse_acier",
  "br.perceuse_a_manivelle",
  "br.fer_a_souder_vintage",
  "br.boite_quincaillerie_metal",
  "br.lot_vis_clous_anciens",
  "br.enclume_petit_modele",
  "br.etau_de_table_regulier",
  "br.lampe_baladeuse_atelier",
  "br.etabli_chene_atelier",
  "br.caisse_outils_chene",
  "br.lot_limes_charpentier",
  "br.ciseaux_a_bois_lot",
  "br.varlope_chene",
  "br.rabot_stanley_no4",
  "br.rabot_bois_artisanal",
  "br.gouge_sculpteur_lot",
  "br.trusquin_acajou_laiton",
  "br.compas_charpentier_xixe",
  "br.mortaisier_acier",
  "br.tariere_charpentier",
  "br.tenailles_forgeron",
  "br.serre_joints_lot",
  "br.plane_charronnier",
  "br.marteau_horloger",
  "br.tournevis_horloger_lot",
  // Bricolage — rares
  "br.outils_peugeot_freres",
  "br.scie_disston_no7",
  "br.rabot_stanley_bedrock",
  "br.coffret_ebeniste_xixe",
  "br.etabli_compagnonnage_xixe",
  "br.singer_fonte_xixe",
  "br.tour_a_bois_atelier",
  "br.enclume_grande_forge",
  "br.outils_compagnon_devoir",
  "br.coffret_dessin_industriel",
  "br.tariere_grande_xviiie",
  "br.balance_romaine_fonte",
  // Bricolage — légendaires & unique
  "leg.br.scie_japonaise_edo",
  "leg.br.coffret_compagnon_signe",
  "leg.br.tour_holtzapffel_xixe",
  "uniq.br.coffre_outils_louis_xiv",
]);

export function getItemImageUrl(templateId: string): string | null {
  return ITEMS_WITH_IMAGE.has(templateId)
    ? `/items/${templateId}.png`
    : null;
}
