import { albumDe } from "@/data/pieces";

/** Ids dont l'art définitif est livré dans public/cartes/ ou public/timbres/.
 *  Les 50 timbres : pipeline `scripts/generate-timbres.mjs` (gabarit commun +
 *  planches 3×3 Gemini découpées), 2026-09-02. Les 50 cartes : pipeline
 *  `scripts/generate-cartes.mjs` (planches 3×3 en 4:3, illustration SEULE —
 *  le cadre est un fond peint par rareté composé par `CarteDuel`), 2026-09-04. */
export const PIECES_AVEC_IMAGE: ReadonlySet<string> = new Set<string>([
  "carte.baby_foot_de_competition_minibon_homologue",
  "carte.boite_d_outils_de_manufacture_signee",
  "carte.boite_musique_ancienne",
  "carte.boite_outils_complete",
  "carte.bottes_camperos_cuir",
  "carte.bronze_animalier",
  "carte.cafetiere_emaillee_50s",
  "carte.chapeau_feutre_50s",
  "carte.coffret_loupes_lecture",
  "carte.enclume_petit_modele",
  "carte.encrier_argent_xixe",
  "carte.encrier_porcelaine_xixe",
  "carte.etabli_pliant_ancien",
  "carte.borne_arcade_mini",
  "carte.flipper_a_plateau_annees_60",
  "carte.guitare_classique_ancienne",
  "carte.harmonica_chromatique_de_bluesman",
  "carte.la_petite_robe_noire_chaine_1925",
  "carte.lampe_bureau_artdeco",
  "carte.lampe_huile_biblio",
  "carte.machine_a_coudre_en_fonte_a_pedale_xixe",
  "carte.manette_megadrive",
  "carte.manuscrit_enlumine_xve",
  "carte.marteau_menuisier",
  "carte.masque_tribal_decoratif",
  "carte.metronome_mecanique_a_pyramide",
  "carte.montre_doree_vintage",
  "carte.ours_en_peluche_mohair_recent",
  "carte.vase_en_verre_moule_laluck_signe",
  "carte.rabot_d_ebeniste_a_semelle_modele_605",
  "carte.radio_cassette_annees_80",
  "carte.robe_50s_pinup",
  "carte.sac_a_main_talaria",
  "carte.saxophone_alto_professionnel",
  "carte.scie_egoine_de_charpentier",
  "carte.service_the_faience",
  "carte.boite_de_construction_metallique_no_3",
  "carte.stylo_plume_haut_de_gamme_a_l_etoile_blanche_d",
  "carte.stylo_waterman_vintage",
  "carte.tabouret_bois_patine",
  "carte.boite_marqueterie_florentine",
  "carte.tourne_disque_a_courroie_vintage",
  "carte.uf_joaillier_imperial_en_email_replique",
  "carte.ukulele_soprano",
  "carte.vase_art_deco_bebert_germain",
  "carte.vase_en_cristal_baraka",
  "carte.vase_galle_signe",
  "carte.veste_smoking_msg",
  "carte.violon_de_maitre_cremonais_1715",
  "carte.yo_yo_duncan_alu",
  "timbre.arenes_de_nimes",
  "timbre.autocar_route_des_alpes",
  "timbre.ballon_monte_1870",
  "timbre.bebert_bahut",
  "timbre.cerf_en_brame",
  "timbre.chateau_de_chambord",
  "timbre.chouette_hulotte",
  "timbre.cremaillere_du_mont_bleu",
  "timbre.croisiere_du_nil_1932",
  "timbre.dark_father",
  "timbre.dirigeable_aurore",
  "timbre.foxy_crush",
  "timbre.grand_max",
  "timbre.grand_tetras_surcharge",
  "timbre.guerre_galactique_1978",
  "timbre.gypaete_barbu",
  "timbre.herisson_d_europe",
  "timbre.hydravion_ligne_sud",
  "timbre.judith_loiseau",
  "timbre.laluck_verrier",
  "timbre.le_petit_moustachu",
  "timbre.le_plombier_sauteur",
  "timbre.legende_de_solda",
  "timbre.loups_des_steppes",
  "timbre.loutre_de_riviere",
  "timbre.lynx_boreal",
  "timbre.mesange_bleue",
  "timbre.mont_saint_michel",
  "timbre.opera_garnier",
  "timbre.orient_express_quai_7",
  "timbre.ours_des_pyrenees",
  "timbre.palais_ideal",
  "timbre.paquebot_etoile_du_nord",
  "timbre.paul_nazamour",
  "timbre.phare_de_cordouan",
  "timbre.phare_de_ker_avel",
  "timbre.picassiette",
  "timbre.pocket_monster_jungle",
  "timbre.pont_des_arts",
  "timbre.premier_vol_postal_1925",
  "timbre.renard_roux",
  "timbre.ridor_couturier",
  "timbre.roland_duff",
  "timbre.stevranos",
  "timbre.titou_cap_sur_la_lune",
  "timbre.tour_de_l_horloge",
  "timbre.tour_eiffel_erreur_de_couleur",
  "timbre.trolling_sons",
  "timbre.viaduc_de_garabit",
  "timbre.victor_de_la_brasse",
]);

export function pieceImageSrc(id: string, declarees: ReadonlySet<string> = PIECES_AVEC_IMAGE): string | null {
  if (!declarees.has(id)) return null;
  const album = albumDe(id);
  if (album === "classeur") return `/cartes/${id}.webp`;
  if (album === "timbres") return `/timbres/${id}.webp`;
  return null;
}
