name: app
options:
  bundleIdPrefix: com.guigousse.broc
  deploymentTarget:
    iOS: 13.0
fileGroups: [../../src]
configs:
  debug: debug
  release: release
settingGroups:
  app:
    base:
      PRODUCT_NAME: Broc
      PRODUCT_BUNDLE_IDENTIFIER: com.guigousse.broc
      DEVELOPMENT_TEAM: 9D78779LKL
packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads
    from: 12.0.0
targetTemplates:
  app:
    type: application
    sources:
      - path: Sources
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      groups: [app]
targets:
  app_iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Assets.xcassets
      - path: Externals
      - path: app_iOS
      - path: assets
        buildPhase: resources
        type: folder
      - path: LaunchScreen.storyboard
    info:
      path: app_iOS/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: [arm64, metal]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: "1.0.0"
        ITSAppUsesNonExemptEncryption: false
        GADApplicationIdentifier: ca-app-pub-6928338731034491~1504112334
        NSUserTrackingUsageDescription: "Your permission allows us to show more relevant ads when you choose to watch one for an in-game bonus."
        CFBundleLocalizations: [en, fr, es, el]
        SKAdNetworkItems:
          - SKAdNetworkIdentifier: cstr6suwn9.skadnetwork
          - SKAdNetworkIdentifier: 4fzdc2evr5.skadnetwork
          - SKAdNetworkIdentifier: 2fnua5tdw4.skadnetwork
          - SKAdNetworkIdentifier: ydx93a7ass.skadnetwork
          - SKAdNetworkIdentifier: p78axxw29g.skadnetwork
          - SKAdNetworkIdentifier: v72qych5uu.skadnetwork
          - SKAdNetworkIdentifier: ludvb6z3bs.skadnetwork
          - SKAdNetworkIdentifier: cp8zw746q7.skadnetwork
          - SKAdNetworkIdentifier: 3sh42y64q3.skadnetwork
          - SKAdNetworkIdentifier: c6k4g5qg8m.skadnetwork
          - SKAdNetworkIdentifier: s39g8k73mm.skadnetwork
          - SKAdNetworkIdentifier: wg4vff78zm.skadnetwork
          - SKAdNetworkIdentifier: 3qy4746246.skadnetwork
          - SKAdNetworkIdentifier: f38h382jlk.skadnetwork
          - SKAdNetworkIdentifier: hs6bdukanm.skadnetwork
          - SKAdNetworkIdentifier: mlmmfzh3r3.skadnetwork
          - SKAdNetworkIdentifier: v4nxqhlyqp.skadnetwork
          - SKAdNetworkIdentifier: wzmmz9fp6w.skadnetwork
          - SKAdNetworkIdentifier: su67r6k2v3.skadnetwork
          - SKAdNetworkIdentifier: yclnxrl5pm.skadnetwork
          - SKAdNetworkIdentifier: t38b2kh725.skadnetwork
          - SKAdNetworkIdentifier: 7ug5zh24hu.skadnetwork
          - SKAdNetworkIdentifier: gta9lk7p23.skadnetwork
          - SKAdNetworkIdentifier: vutu7akeur.skadnetwork
          - SKAdNetworkIdentifier: y5ghdn5j9k.skadnetwork
          - SKAdNetworkIdentifier: v9wttpbfk9.skadnetwork
          - SKAdNetworkIdentifier: n38lu8286q.skadnetwork
          - SKAdNetworkIdentifier: 47vhws6wlr.skadnetwork
          - SKAdNetworkIdentifier: kbd757ywx3.skadnetwork
          - SKAdNetworkIdentifier: 9t245vhmpl.skadnetwork
          - SKAdNetworkIdentifier: a2p9lx4jpn.skadnetwork
          - SKAdNetworkIdentifier: 22mmun2rn5.skadnetwork
          - SKAdNetworkIdentifier: 44jx6755aq.skadnetwork
          - SKAdNetworkIdentifier: k674qkevps.skadnetwork
          - SKAdNetworkIdentifier: 4468km3ulz.skadnetwork
          - SKAdNetworkIdentifier: 2u9pt9hc89.skadnetwork
          - SKAdNetworkIdentifier: 8s468mfl3y.skadnetwork
          - SKAdNetworkIdentifier: klf5c3l5u5.skadnetwork
          - SKAdNetworkIdentifier: ppxm28t8ap.skadnetwork
          - SKAdNetworkIdentifier: kbmxgpxpgc.skadnetwork
          - SKAdNetworkIdentifier: uw77j35x4d.skadnetwork
          - SKAdNetworkIdentifier: 578prtvx9j.skadnetwork
          - SKAdNetworkIdentifier: 4dzt52r2t5.skadnetwork
          - SKAdNetworkIdentifier: tl55sbb4fm.skadnetwork
          - SKAdNetworkIdentifier: c3frkrj4fj.skadnetwork
          - SKAdNetworkIdentifier: e5fvkxwrpn.skadnetwork
          - SKAdNetworkIdentifier: 8c4e2ghe7u.skadnetwork
          - SKAdNetworkIdentifier: 3rd42ekr43.skadnetwork
          - SKAdNetworkIdentifier: 97r2b46745.skadnetwork
          - SKAdNetworkIdentifier: 3qcr597p9d.skadnetwork
    entitlements:
      path: app_iOS/app_iOS.entitlements
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      base:
        ENABLE_BITCODE: false
        ARCHS: [arm64, x86_64]
        VALID_ARCHS: arm64  x86_64 
        LIBRARY_SEARCH_PATHS[arch=x86_64]: $(inherited) $(PROJECT_DIR)/Externals/x86_64/$(CONFIGURATION) $(SDKROOT)/usr/lib/swift $(DEVELOPER_DIR)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(PLATFORM_NAME) $(DEVELOPER_DIR)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/$(PLATFORM_NAME)
        LIBRARY_SEARCH_PATHS[arch=arm64]: $(inherited) $(PROJECT_DIR)/Externals/arm64/$(CONFIGURATION) $(SDKROOT)/usr/lib/swift $(DEVELOPER_DIR)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(PLATFORM_NAME) $(DEVELOPER_DIR)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/$(PLATFORM_NAME)
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        EXCLUDED_ARCHS[sdk=iphoneos*]: x86_64
      groups: [app]
    dependencies:
      - package: GoogleMobileAds
      - framework: libapp.a
        embed: false
      - sdk: CoreGraphics.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: QuartzCore.framework
      - sdk: Security.framework
      - sdk: UIKit.framework
      - sdk: WebKit.framework
    preBuildScripts:
      - script: npm run -- tauri ios xcode-script -v --platform ${PLATFORM_DISPLAY_NAME:?} --sdk-root ${SDKROOT:?} --framework-search-paths "${FRAMEWORK_SEARCH_PATHS:?}" --header-search-paths "${HEADER_SEARCH_PATHS:?}" --gcc-preprocessor-definitions "${GCC_PREPROCESSOR_DEFINITIONS:-}" --configuration ${CONFIGURATION:?} ${FORCE_COLOR} ${ARCHS:?}
        name: Build Rust Code
        basedOnDependencyAnalysis: false
        outputFiles:
          - $(SRCROOT)/Externals/x86_64/${CONFIGURATION}/libapp.a
          - $(SRCROOT)/Externals/arm64/${CONFIGURATION}/libapp.a